# =================================================================================================
#     Input Data
# =================================================================================================

# Set the input data, using absolute file paths (relative paths do not work well with some
# of the snakemake tools we are using in the pipeline, such as shadow directories).
data:

  # Input table that lists all samples with their units and fastq files.
  # Paths in the table need to be absolute! No relative paths (e.g., `../data`)!
  samples: "/path/to/data/samples.tsv"

  reference:

    # Name of the reference genome. Only used if settings:snpeff is set to `true`.
    # This has to be a valid snpeff database genome name.
    name: "Arabidopsis_thaliana"

    # Path to the reference genome in fasta format.
    # Path needs to be absolute! No relative path (e.g., `../ref`)!
    genome: "/path/to/data/genome.fa"

    # Path to any database of known variants (in vcf or vcf.gz format),
    # ideally as it is provided by the GATK bundle.
    # If no such file is available, use an empty list or string instead.
    # Path needs to be absolute! No relative path (e.g., `../var`)!
    known-variants: ""

# =================================================================================================
#     Pipeline Settings
# =================================================================================================

settings:

  # Select the tool used for read trimming.
  # Valid values: "adapterremoval", "cutadapt", "fastp", "skewer", "trimmomatic"
  trimming-tool: "trimmomatic"

  # Select whether to merge paired end reads into a single read while trimming.
  # Only works with adapterremoval and fastp;
  # cannot be used with cutadapt, skewer, or trimmomatic, as those do not support merging reads.
  merge-paired-end-reads: false

  # Select the tool used for read mapping.
  # Valid values: "bwamem", "bwaaln", "bowtie2"
  mapping-tool: "bwamem"

  # After mapping, and before any subsequent steps (deduplication, variant calling etc),
  # appy a filtering step using `samtools view`. If set to `true`,
  # use 'params: samtools: view' below to set the actual filtering parameters being used.
  # This step is for example useful when working with ancient DNA, where such filtering is common.
  filter-mapped-reads: false

  # Select whether to mark and remove duplicates after mapping,
  # using either picard/markduplicates or dedup, depending on "settings: duplicates-tool"
  remove-duplicates: true

  # Select the tool to mark duplicates.
  # Valid values: "picard", "dedup"
  duplicates-tool: "picard"

  # Select whether to recalibrate base frequencies after mapping, using gatk/baserecalibrator
  recalibrate-base-qualities: false

  # Select the tool used for SNP calling.
  # Valid values: "haplotypecaller", "bcftools", "freebayes"
  calling-tool: "haplotypecaller"

  # Uncomment and point to a bed file with, e.g., captured regions if necessary,
  # see https://gatkforums.broadinstitute.org/gatk/discussion/4133/when-should-i-use-l-to-pass-in-a-list-of-intervals
  # restrict-regions: captured_regions.bed

  # If regions are restricted, uncomment this to enlarge them by the given value
  # in order to include flanking areas.
  # region-padding: 100

  # Set to true in order to run snpeff annotations, which always requires the full SNP calling
  # pipleline to run. Set to false instead if this is not required/desired, for example when
  # using the workflow to only obtain quality control statistics.
  snpeff: true

  # Set to true in order to run mapDamage.
  mapdamage: false

  # Set to true in order to run DamageProfiler.
  damageprofiler: false

  # Set to true to compute a table of allele frequencies from the filtered vcf,
  # using the `AD` (allelic depth) field of the vcf for each sample to compute the total count
  # (coverage), frequency of REF/(REF+ALT) counts, and REF and ALT counts, for biallelic SNP sites.
  # Note that this table only contains sites that are present in the filtered vcf.
  # Hence, for pool sequencing data, you also should consider to set thresholds for the calling
  # to low values so that sites are considered as variants that have low frequency alleles in the
  # pool. Typically, when working with individuals instead of pooled data, such sites would rather
  # be considered sequencing errors instead of low frequencies.
  frequency-table: false

  # If the above flag is set to true, this comma separated list is used to decide which values
  # to put into the table. Valid values: "COV,FREQ,REF_CNT,ALT_CNT"
  frequency-table-fields: "COV,FREQ,REF_CNT,ALT_CNT"

# =================================================================================================
#     Tool Parameters
# =================================================================================================

params:

  # ----------------------------------------------------------------------
  #     adapterremoval
  # ----------------------------------------------------------------------

  # Used only if settings:trimming-tool == adapterremoval
  # See adapterremoval manual: https://adapterremoval.readthedocs.io/en/latest/
  # and https://adapterremoval.readthedocs.io/en/latest/manpage.html
  adapterremoval:
    threads: 4

    # Extra parameters for single reads. Param `--gzip` is alreaday set internally.
    se: ""

    # Extra parameters for paired end reads. Param `--gzip` is alreaday set internally,
    # as well as `--collapse` if settings:merge-paired-end-reads is set to true above.
    pe: ""

  # ----------------------------------------------------------------------
  #     cutadapt
  # ----------------------------------------------------------------------

  # Used only if settings:trimming-tool == cutadapt
  # See cutadapt manual: https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types
  cutadapt:
    threads: 4

    # Set the adapters and any extra parameters.
    # For example, adapters: "-a AGAGCACACGTCTGAACTCCAGTCAC -g AGATCGGAAGAGCACACGT -A AGAGCACACGTCTGAACTCCAGTCAC -G AGATCGGAAGAGCACACGT"
    # extra: "--minimum-length 1 -q 20"

    # Extra parameters for single reads.
    se:
      adapters: "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
      extra: "-q 20"

    # Extra parameters for paired end reads.
    pe:
      adapters: "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
      extra: "-q 20"

  # ----------------------------------------------------------------------
  #     fastp
  # ----------------------------------------------------------------------

  # Used only if settings:trimming-tool == fastp
  # See fastp manual: https://github.com/OpenGene/fastp
  fastp:
    threads: 4

    # Extra parameters for single reads.
    se: ""

    # Extra parameters for paired end reads.
    pe: ""

  # ----------------------------------------------------------------------
  #     skewer
  # ----------------------------------------------------------------------

  # Used only if settings:trimming-tool == skewer
  # See skewer manual: https://github.com/relipmoc/skewer
  # By default, we internally already set the options `--format sanger --compress`
  skewer:
    threads: 4

    # Extra parameters for single reads.
    se: "--mode any"

    # Extra parameters for paired end reads.
    pe: "--mode pe"

  # ----------------------------------------------------------------------
  #     trimmomatic
  # ----------------------------------------------------------------------

  # Used only if settings:trimming-tool == trimmomatic
  # See trimmomatic manual: http://www.usadellab.org/cms/?page=trimmomatic
  trimmomatic:
    threads: 6
    se:
      extra: ""
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
    pe:
      extra: ""
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"

  # ----------------------------------------------------------------------
  #     bowtie2
  # ----------------------------------------------------------------------

  # Used only if settings:mapping-tool == bowtie2
  # See bowtie2 manual: http://bowtie-bio.sourceforge.net/bowtie2/index.shtml
  bowtie2:
    threads: 12

    # Extra parameters. We internally already set `--rg` and `--rg-id`
    extra: ""

  # ----------------------------------------------------------------------
  #     bwa aln
  # ----------------------------------------------------------------------

  # Used only if settings:mapping-tool == bwaaln
  # See bwa manual: http://bio-bwa.sourceforge.net/
  bwaaln:
    threads: 4

    # Extra parameters for bwa aln.
    extra: ""

    # Extra parameters for bwa sam(se/pe), which turns the bwa aln (*.sai) files into bam files.
    # We internally already set `-r` to use read group ("@RG") tags "ID" and "SM".
    # Note that we use samse or sampe depending on which type each sample is (single-end or
    # paired-end).
    extra-sam: ""

    # Extra parameters for samtools, which we use after bwa aln for sorting its output.
    extra-sort: ""

  # ----------------------------------------------------------------------
  #     bwa mem
  # ----------------------------------------------------------------------

  # Used only if settings:mapping-tool == bwamem
  # See bwa manual: http://bio-bwa.sourceforge.net/
  bwamem:
    threads: 12

    # Extra parameters for bwa mem.
    # We internally already set `-R` to use read group ("@RG") tags "ID" and "SM".
    extra: ""

    # Extra parameters for samtools, which we use after bwa mem for sorting its output.
    extra-sort: ""

  # ----------------------------------------------------------------------
  #     samtools view
  # ----------------------------------------------------------------------

  # Used only if settings:filter-mapped-reads == true
  # See http://www.htslib.org/doc/samtools.html
  samtools:

    # Extra parameters for samtools/view.
    # These are the optional filtering criteria that are used beween mapping and subsequent steps.
    # We also always add `-b` to this, so that the output is in the binary format that we expect
    # for our subsequent steps.
    view: "-q 1"

  # ----------------------------------------------------------------------
  #     picard
  # ----------------------------------------------------------------------

  # Used only if settings:duplicates-tool == picard
  picard:
    # Extra parameters for MarkDuplicates.
    # See https://gatk.broadinstitute.org/hc/en-us/articles/360057439771-MarkDuplicates-Picard
    MarkDuplicates: "REMOVE_DUPLICATES=true"

    # Run several Picard QC tools, as needed, using Picard CollectMultipleMetrics.
    # See https://gatk.broadinstitute.org/hc/en-us/articles/360042478112-CollectMultipleMetrics-Picard
    CollectMultipleMetrics:
      AlignmentSummaryMetrics: True
      BaseDistributionByCycle: True
      GcBiasMetrics: True
      InsertSizeMetrics: True
      QualityByCycleMetrics: True
      QualityScoreDistributionMetrics: True
      QualityYieldMetrics: True
      # RnaSeqMetrics: False

      # Extra parameters for CollectMultipleMetrics
      extra:
        "VALIDATION_STRINGENCY=LENIENT METRIC_ACCUMULATION_LEVEL=null METRIC_ACCUMULATION_LEVEL=SAMPLE"

  # ----------------------------------------------------------------------
  #     dedup
  # ----------------------------------------------------------------------

  # Used only if settings:duplicates-tool == dedup
  # See https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/dedupe-guide/
  dedup:
    extra: "-m"

  # ----------------------------------------------------------------------
  #     bcftools
  # ----------------------------------------------------------------------

  # Used only if settings:calling-tool == bcftools
  # See http://samtools.github.io/bcftools/bcftools.html
  bcftools:
    threads: 8

    # Extra parameters for the mpileup step.
    mpileup: "--max-depth 10000"

    # Extra parameters for the bcftools call step.
    call: ""

  # ----------------------------------------------------------------------
  #     freebayes
  # ----------------------------------------------------------------------

  # Used only if settings:calling-tool == freebayes
  # See https://github.com/freebayes/freebayes
  freebayes:
    # Extra parameters for freebayes.
    extra: ""

    # Settings for parallelization
    threads: 8
    compress-threads: 2
    chunksize: 100000

  # ----------------------------------------------------------------------
  #     gatk
  # ----------------------------------------------------------------------

  gatk:
    # Used only if settings:recalibrate-base-qualities == true
    # Extra parameters for BaseRecalibrator,
    # see https://gatk.broadinstitute.org/hc/en-us/articles/360036803991-HaplotypeCaller
    BaseRecalibrator: ""

    # Used only if settings:calling-tool == haplotypecaller
    # Extra parameters for HaplotypeCaller and surrounding steps,
    # see https://gatk.broadinstitute.org/hc/en-us/articles/360036898312-BaseRecalibrator
    HaplotypeCaller: ""
    HaplotypeCaller-threads: 2
    GenotypeGVCFs: ""

  # ----------------------------------------------------------------------
  #     gatk / variantfiltration
  # ----------------------------------------------------------------------

  variantfiltration-hard:
    # Extra parameters for the hard filtering as outlined in GATK docs
    # https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set
    # The filtering is separated for SNPs/SNVs and indels.
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"

  # ----------------------------------------------------------------------
  #     fastqc
  # ----------------------------------------------------------------------

  fastqc:
    # Select input files for fastqc: either "samples" for the raw sequence input files,
    # or "trimmed" for the fastq files resulting from the trimming step.
    input: "samples"

    # Additional parameters for fastqc
    # See https://www.bioinformatics.babraham.ac.uk/projects/fastqc/
    extra: ""

  # ----------------------------------------------------------------------
  #     qualimap
  # ----------------------------------------------------------------------

  qualimap:
    # Additional parameters for qualimap, see http://qualimap.conesalab.org/
    extra: ""
    threads: 2

  # ----------------------------------------------------------------------
  #     snpeff
  # ----------------------------------------------------------------------

  snpeff:
    # Additional parameters for snpeff, see https://pcingola.github.io/SnpEff/se_commandline/
    # Used only if settings:snpeff == true
    extra: "-Xmx4g"

  # ----------------------------------------------------------------------
  #     mapdamage
  # ----------------------------------------------------------------------

  mapdamage:
    # Additional parameters for mapdamage, see http://ginolhac.github.io/mapDamage/
    # Used only if settings:mapdamage == true
    extra: ""

  # ----------------------------------------------------------------------
  #     damageprofiler
  # ----------------------------------------------------------------------

  damageprofiler:
    # Additional parameters for damageprofiler, see https://damageprofiler.readthedocs.io/en/latest/contents/generalUsage.html
    # Used only if settings:damageprofiler == true
    extra: ""

  # ----------------------------------------------------------------------
  #     multiqc
  # ----------------------------------------------------------------------

  multiqc:
    # Additional parameter for multiqc, see https://multiqc.info/
    # You can for example specify an additional MultiQC config file here, by using
    # `--config /path/to/multiqc-config.yaml`.
    extra: ""
