$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file for the grenepipe workflow

type: object

properties:
  data:
    type: object
    properties:
      samples:
        type: string
      reference:
        type: object
        properties:
          name:
            type: string
          genome:
            type: string
          known-variants:
            type: string
        required:
          - genome
    required:
      - samples
      - reference

  settings:
    type: object
    properties:
      remove-duplicates:
        type: boolean
      recalibrate-base-qualities:
        type: boolean
      trimming-tool:
        type: string
        enum: ["cutadapt", "trimmomatic", "skewer"]
      mapping-tool:
        type: string
        enum: ["bwamem", "bowtie2"]
      duplicates-tool:
        type: string
        enum: ["picard", "dedup"]
      calling-tool:
        type: string
        enum: ["haplotypecaller", "freebayes", "bcftools"]
      restrict-regions:
        type: string
      region-padding:
        type: integer
      vqsr:
        type: boolean
    required:
      - remove-duplicates
      - recalibrate-base-qualities
      - trimming-tool
      - mapping-tool
      - calling-tool
      - vqsr

  params:
    type: object
    properties:
      trimmomatic:
        type: object
        properties:
          threads:
            type: integer
          pe:
            type: object
          se:
            type: object
      bwamem:
        type: object
        properties:
          threads:
            type: integer
      skewer:
        type: object
        properties:
          threads:
            type: integer
          se:
            type: string
          pe:
            type: string
      bowtie2:
        type: object
        properties:
          threads:
            type: integer
      picard:
        type: object
        properties:
          MarkDuplicates:
            type: string
        required:
          - MarkDuplicates
      dedup:
        type: object
        properties:
          extra:
            type: string
      bcftools:
        type: object
        properties:
          mpileup:
            type: string
          call:
            type: string
          threads:
            type: integer
          # concat:
          #   type: string
      freebayes:
        type: object
        properties:
          extra:
            type: string
          chunksize:
            type: integer
          threads:
            type: integer
          compress-threads:
            type: integer
      gatk:
        type: object
        properties:
          HaplotypeCaller:
            type: string
          HaplotypeCaller-threads:
            type: integer
          BaseRecalibrator:
            type: string
          GenotypeGVCFs:
            type: string
          VariantRecalibrator:
            type: string
        required:
          - GenotypeGVCFs
      variantfiltration-hard:
        type: object
        properties:
          snvs:
            type: string
          indels:
            type: string
        required:
          - snvs
          - indels
    required:
      - trimmomatic
      - picard
      - gatk
      - variantfiltration-hard

required:
  - data
  - settings
  - params
